lang: ruby
# Replace any and all occurrences of http with https
script:
  - find . -not -path '*/\.*' -type f -print0 | xargs -0 sed -i 's/http:\/\//https:\/\//g'
# Then push to Github
after_sucess:
  - .travis/push.sh
env:
  global:
    secure: bFwyqq0wNzxliIa7wwIdKd+MaQKyBQaAlhQfESCd8e4Z27Goqn3UUYTsu7yWg7vTaMqvYZXqhZNPRZYf4wKH3JsAldggkBQoaQ3j3EJm3Awd8kbx2GV9PW8qKiYM/9nCRtek6czpugG/Q2B1mxn2279QwvxzFmlHWxBC3bYBchE3pqTu1L0gHPmrQUAOGbQm4X25mkiIhnVUF6yMrnvuzcb8vcpkdpCT09r07IMKOTHiRYyzDV+kJET32UdKPuvy+mYvTI3b2Y2It+BdEK/enGgwI3HLrirBzaFAnI0g/28BA9T5HGNONZFBpOqMADhN4aP7mAMMEqeUjUZivqHR2dZ3+Pupe5L2xAyrNVlpTmfBAvLbgM9Xo20C6EakQXFgn9J/2exh2NN6BAKiNujOmp9WLrrki85OCKBST/81SYI0TBY0IhsYjx/i+YqTGg3EN96xErQZ0gz4ryzF65oeG91MWcM0i09vL/SBiyyQ8Ob7PJwliYAXThjZVUrh6PSZaXFiwxzL4oWd1WTUw+IK4vMzeSc4IP/bATjl9tSO9vc6rYERZoXH3oVsIr14oVctkABeZF6jpplFHPT9k0NHHAjHUbcQ893MTdtxO+XWTDruhRAE2uqXBhn44EsDNQozvnkjR3/ImWho/vXX6XhB+ya3vHrhl5oRUoRA0ErA1Ik=
